
-- DROP INDEX PROPERTY_GROUP_TABLE__GENERAL_GROUP__INDEX;
-- ALTER TABLE PROPERTY_GROUP_TABLE DROP COLUMN general_group ;

ALTER TABLE PROPERTY_GROUP_TABLE ADD COLUMN general_group BOOLEAN NOT NULL DEFAULT true;
CREATE INDEX PROPERTY_GROUP_TABLE__GENERAL_GROUP__INDEX ON PROPERTY_GROUP_TABLE(general_group);




